# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Verify Files Modify'
description: 'Verify PR files modification.'
author: 'xrkffgg'

branding:
  icon: 'align-justify'
  color: 'red'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  skip-verify-authority:
    description: Skip verify by creator authority.
  skip-verify-users:
    description: Skip verify by github userid.
  skip-label:
    description: Skip verify by pr label.
  skip-count:
    description: Skip verify by commits count.
  forbid-files:
    description: Forbid files. Higher than allowed.
  forbid-paths:
    description: Forbid paths. Higher than allowed.
  allowed-files:
    description: Allowed files.
  allowed-paths:
    description: Allowed paths.
  comment:
    description: Comment when verification success.
  comment-mark:
    description: Comment mark to find.
  assignees:
    description: Assignees when verification success.
  close:
    description: Close PR when verification success.
  set-failed:
    description: When hit, whether set failed.

runs:
  using: 'node20'
  main: 'dist/index.js'
